// floppy.h - runtime file-loading API for the floppy-disk build target
// (see docs/floppy.md).
//
// This is the demo-facing counterpart to tools/floppy/loader.c's resident
// loader -- analogous to include/loci.c's file_load()/loci_present(), but
// for the FloppyBuilder-compatible disk target instead of a LOCI device.
// Files are addressed by a small compile-time integer index (the
// LOADER_*_FILE #defines in the FloppyBuilder-generated
// build/floppy_directory.h), not a runtime path string -- a real,
// intentional difference from loci.c's API, not an oversight: on this
// target there is no directory/filesystem to search at runtime, only a
// fixed table of files baked into the disk image at build time.
//
// Fixed API cells below MUST exactly match tools/floppy/loader.c's own
// addresses -- these two files are compiled completely separately (the
// loader is its own standalone program, embedded into the disk image by
// tools/oric_floppybuilder.py; this file is linked into the demo binary),
// so nothing enforces this agreement except both files' own comments.

#ifndef FLOPPY_H
#define FLOPPY_H

#include <stdint.h>

// Fixed resident-loader API cells (plain memory addresses -- pointer-
// dereference style, since this file is used from normal C, unlike
// tools/floppy/loader.c's own plain-integer versions of these same
// addresses, needed there for raw asm bracket-notation operands instead).
#define FLOPPY_API_SECTOR    (*(volatile uint8_t*)0xFFEF)
#define FLOPPY_API_TRACK     (*(volatile uint8_t*)0xFFF0)
#define FLOPPY_API_SIZE_LO   (*(volatile uint8_t*)0xFFF1)
#define FLOPPY_API_SIZE_HI   (*(volatile uint8_t*)0xFFF2)
#define FLOPPY_API_DEST_LO   (*(volatile uint8_t*)0xFFF4)
#define FLOPPY_API_DEST_HI   (*(volatile uint8_t*)0xFFF5)

// Loads file_index (see build/floppy_directory.h's LOADER_*_FILE
// #defines, generated by tools/oric_floppybuilder.py) into dst, capped at
// max_size. Returns the file's real size (from the generated
// FloppyFileSize[] table) on success, or -1 if it doesn't fit max_size.
// Synchronous -- returns to the caller like loci.c's file_load(), not
// like the OSDK reference's InitializeFileAt/forever_loop chaining (see
// docs/floppy.md's "Effects"-equivalent section, "What's simplified").
int16_t floppy_load(uint8_t file_index, void *dst, uint16_t max_size);

#pragma compile("floppy.c")

#endif // FLOPPY_H
