// floppy.c - see floppy.h.

#include "floppy.h"
#include "floppy_directory.h"   // generated by tools/oric_floppybuilder.py -- FloppyFileStartSector/Track/Size[]

int16_t floppy_load(uint8_t file_index, void *dst, uint16_t max_size)
{
    uint16_t size = FloppyFileSize[file_index];
    uint16_t dest = (uint16_t)dst;

    if (size > max_size)
        return -1;

    FLOPPY_API_SECTOR  = FloppyFileStartSector[file_index];
    FLOPPY_API_TRACK   = FloppyFileStartTrack[file_index];
    FLOPPY_API_SIZE_LO = (uint8_t)(size & 0xFF);
    FLOPPY_API_SIZE_HI = (uint8_t)(size >> 8);
    FLOPPY_API_DEST_LO = (uint8_t)(dest & 0xFF);
    FLOPPY_API_DEST_HI = (uint8_t)(dest >> 8);

    __asm { jsr 0xFFF7 }

    return (int16_t)size;
}
