#!/usr/bin/env python3
"""oric_ttfconv.py - convert a TTF font into a proportional Oric HIRES
bitmap font, for use with include/ttf.c/h's runtime renderer.

API shape (a `TtfFont` descriptor: fixed height, per-glyph pixel width,
per-glyph byte width, per-glyph offset into a shared glyph-data blob, plus
alignment-aware print helpers) is inspired by raxiss/iss000's lib-ttf
(github.com/iss000/oricOpenLibrary/tree/main/lib-ttf) -- credit where due
for the *concept* of a proportional bitmap font with this descriptor shape.
This is NOT a port of that project's code: lib-ttf's own offline pipeline
is Lua + ImageMagick producing 6502-assembly data tables for a hand-written
asm renderer; this tool is pure Python using Pillow's built-in TrueType
rasterization (already a dependency of tools/oric_pictconv.py), and the
runtime side (include/ttf.c) is plain Oscar64 C built on the same
hb_put()-based per-pixel rendering as include/hires.c's hb_put_chars(),
not lib-ttf's 6502 assembly. The on-disk packing format (glyph rows packed
6 pixels/byte, bit5=leftmost, local to each glyph) is this tool's own
convention, not lib-ttf's.

Requires Pillow (see tools/requirements.txt): pip install -r tools/requirements.txt
"""

import argparse
import sys

from PIL import Image, ImageDraw, ImageFont

DEFAULT_FIRST_CHAR = 32
DEFAULT_LAST_CHAR = 126   # printable ASCII, matches include/charset.h's ROM range


def rasterize_font(ttf_path, point_size, first_char, last_char):
    """Rasterize every glyph in [first_char, last_char] to a common baseline
    and height, returning (height, [(width, rows_of_bytes), ...]) where each
    glyph's rows are already thresholded to 1-bit and packed 6px/byte
    (bit5=leftmost, local to the glyph -- not yet placed at any screen x)."""
    font = ImageFont.truetype(ttf_path, point_size)
    ascent, descent = font.getmetrics()
    height = ascent + descent

    glyphs = []
    for code in range(first_char, last_char + 1):
        ch = chr(code)
        width = round(font.getlength(ch))
        if width <= 0:
            # Zero-advance glyph (shouldn't normally happen for printable
            # ASCII) -- still emit an empty glyph rather than skip it, so
            # index arithmetic (code - first_char) stays contiguous.
            glyphs.append((0, []))
            continue

        # Render onto a canvas tall enough for ascent+descent, wide enough
        # for the glyph's own bbox (which can differ from its advance
        # width for e.g. italic overhang) -- canvas width is generous, the
        # glyph's own advance `width` is what's actually packed/used.
        canvas_w = max(width, 1) + 4
        img = Image.new("L", (canvas_w, height), 0)
        draw = ImageDraw.Draw(img)
        draw.text((0, 0), ch, font=font, fill=255)

        px = img.load()
        rows = []
        for y in range(height):
            row_bits = [1 if px[x, y] >= 128 else 0 for x in range(width)]
            rows.append(row_bits)
        glyphs.append((width, rows))

    return height, glyphs


def pack_glyph_bytes(width, rows):
    """Pack one glyph's per-row bit lists into 6px/byte rows (bit5=leftmost
    within the glyph, matching include/oric.h's HIRES pixel-byte bit order
    -- but WITHOUT bit6/bit7, those are added at render time by ttf.c, not
    baked into this data, since this is glyph-local pixel data, not a
    HIRES screen byte)."""
    width_bytes = (width + 5) // 6
    packed = bytearray()
    for row_bits in rows:
        for b in range(width_bytes):
            byte = 0
            for bit in range(6):
                col = b * 6 + bit
                if col < width and row_bits[col]:
                    byte |= 0x20 >> bit
            packed.append(byte)
    return width_bytes, bytes(packed)


def write_header(path, label, height, first_char, last_char, glyphs):
    num_glyphs = last_char - first_char + 1
    widths = []
    width_bytes_list = []
    offsets = []
    char_defs = bytearray()

    for width, rows in glyphs:
        wb, packed = pack_glyph_bytes(width, rows)
        widths.append(width)
        width_bytes_list.append(wb)
        offsets.append(len(char_defs))
        char_defs.extend(packed)

    lines = [
        f"// Generated by tools/oric_ttfconv.py -- {num_glyphs} glyphs, height={height},",
        f"// codes {first_char}-{last_char}. See include/ttf.h for the TtfFont struct",
        "// this initializer targets, and its provenance note re: raxiss/lib-ttf.",
        "",
        f"static const unsigned char {label}_widths[{num_glyphs}] = {{",
        "    " + ", ".join(str(w) for w in widths) + ",",
        "};",
        "",
        f"static const unsigned char {label}_width_bytes[{num_glyphs}] = {{",
        "    " + ", ".join(str(w) for w in width_bytes_list) + ",",
        "};",
        "",
        f"static const unsigned short {label}_offsets[{num_glyphs}] = {{",
        "    " + ", ".join(str(o) for o in offsets) + ",",
        "};",
        "",
        f"static const unsigned char {label}_char_defs[{len(char_defs)}] = {{",
    ]
    for i in range(0, len(char_defs), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in char_defs[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    lines.append(f"const TtfFont {label} = {{")
    lines.append(f"    {max(widths) if widths else 0}, {height},")
    lines.append(f"    {first_char}, {last_char},")
    lines.append(f"    {label}_widths, {label}_width_bytes, {label}_offsets, {label}_char_defs")
    lines.append("};")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("font", help="source .ttf file")
    ap.add_argument("pointsize", type=int, help="rasterization point size")
    ap.add_argument("output", help="output .h file")
    ap.add_argument("--label", default="oric_font", help="C variable name for the TtfFont (default: oric_font)")
    ap.add_argument("--first-char", type=int, default=DEFAULT_FIRST_CHAR)
    ap.add_argument("--last-char", type=int, default=DEFAULT_LAST_CHAR)
    args = ap.parse_args()

    height, glyphs = rasterize_font(args.font, args.pointsize, args.first_char, args.last_char)
    write_header(args.output, args.label, height, args.first_char, args.last_char, glyphs)

    print(f"Wrote {args.output}: {len(glyphs)} glyphs, height={height}px, "
          f"codes {args.first_char}-{args.last_char}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
